"""empty message

Revision ID: 03776c9f130e
Revises: f2e22d687154
Create Date: 2019-04-04 14:36:09.939144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03776c9f130e'
down_revision = 'f2e22d687154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_header_from_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_header_to_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'header_from_id')
    op.drop_column('message', 'header_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('header_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('header_from_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_header_to_id_fkey', 'message', 'message_email_address', ['header_to_id'], ['id'])
    op.create_foreign_key('message_header_from_id_fkey', 'message', 'message_email_address', ['header_from_id'], ['id'])
    # ### end Alembic commands ###
