"""empty message

Revision ID: 48c22ef3a4da
Revises: 91d329363759
Create Date: 2019-04-02 13:58:42.795247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c22ef3a4da'
down_revision = '91d329363759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'message', ['message_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    # ### end Alembic commands ###
