"""empty message

Revision ID: 4b4071daaf3c
Revises: 0c02bba03e98
Create Date: 2019-06-10 11:48:03.033381

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models.mixins.status_mixin import OBJECT_STATUS


# revision identifiers, used by Alembic.
revision = '4b4071daaf3c'
down_revision = '0c02bba03e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('obj_status', sqlalchemy_utils.types.choice.ChoiceType(choices=OBJECT_STATUS), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'obj_status')
    # ### end Alembic commands ###
