"""empty message

Revision ID: 59efc69f6999
Revises: a4540cc0c116
Create Date: 2019-04-20 00:05:40.266679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59efc69f6999'
down_revision = 'a4540cc0c116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'updated')
    op.drop_column('message', 'datetime')
    # ### end Alembic commands ###
