"""Add Message.raw

Revision ID: 91d329363759
Revises: 1693910a7a3b
Create Date: 2019-04-02 13:57:25.055922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d329363759'
down_revision = '1693910a7a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('raw_resource', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'raw_resource')
    # ### end Alembic commands ###
