"""Add Contact.company

Revision ID: 9d8fa0473dfa
Revises: a8e5e4442b83
Create Date: 2019-04-21 22:46:42.225537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8fa0473dfa'
down_revision = 'a8e5e4442b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'company')
    # ### end Alembic commands ###
