"""empty message

Revision ID: a4540cc0c116
Revises: e21fe4da9e63
Create Date: 2019-04-19 23:59:00.817859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4540cc0c116'
down_revision = 'e21fe4da9e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_constraint('email_address_contact_id_fkey', 'email_address', type_='foreignkey')
    op.drop_column('email_address', 'contact_id')
    op.add_column('message', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'updated')
    op.drop_column('message', 'datetime')
    op.add_column('email_address', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('email_address_contact_id_fkey', 'email_address', 'contact', ['contact_id'], ['id'])
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    # ### end Alembic commands ###
