"""empty message

Revision ID: a8e5e4442b83
Revises: 40aa5b2ac167
Create Date: 2019-04-21 11:39:26.044467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e5e4442b83'
down_revision = '40aa5b2ac167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_address', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_address', 'status')
    # ### end Alembic commands ###
