"""user.credentials JSON

Revision ID: cd52fc848f31
Revises: 0ba903396c8a
Create Date: 2019-03-29 22:59:13.445839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd52fc848f31'
down_revision = '0ba903396c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_credentials', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_credentials')
    # ### end Alembic commands ###
